name: Lint YAML

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yamllint
        run: |
          sudo apt-get update && sudo apt-get install yamllint
      - name: Lint YAML files
        run: yamllint .
      - name: Fail on lint errors
        if: failure()
        env:
          CI: true
        run: exit 1
